version: '3.0'
services:

  bd:
    container_name: bd-adopet
    image: mysql:8
    healthcheck:
      test: mysql --protocol=socket -hlocalhost -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'
      interval: 20s
      timeout: 10s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user123"
      MYSQL_DATABASE: "adopet_store"
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      
volumes:
  mysql-data: